spring.application.name=conexion_bd
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=Robert
spring.datasource.password=2302
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver